# Generated by Django 5.0.14 on 2026-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0002_rename_events_tenant_event_created_idx_events_tenant__34f0a2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("booking", "Booking"),
                    ("job", "Job"),
                    ("user", "User"),
                    ("property", "Property"),
                    ("service", "Service"),
                    ("memory", "Memory"),
                    ("technician", "Technician"),
                    ("brief", "Brief"),
                ],
                db_index=True,
                help_text="Type of entity this event relates to",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("booking.created", "Booking Created"),
                    ("booking.confirmed", "Booking Confirmed"),
                    ("booking.cancelled", "Booking Cancelled"),
                    ("booking.completed", "Booking Completed"),
                    ("booking.fulfilled", "Booking Fulfilled"),
                    ("booking.rescheduled", "Booking Rescheduled"),
                    ("booking.job_generated", "Booking Job Generated"),
                    ("job.assigned", "Job Assigned"),
                    ("job.claimed", "Job Claimed"),
                    ("job.released", "Job Released"),
                    ("job.started", "Job Started"),
                    ("job.completed", "Job Completed"),
                    ("job.cancelled", "Job Cancelled"),
                    ("technician.assigned", "Technician Assigned"),
                    ("technician.unassigned", "Technician Unassigned"),
                    ("technician.checked_in", "Technician Checked In"),
                    ("technician.checked_out", "Technician Checked Out"),
                    ("technician.skills_updated", "Technician Skills Updated"),
                    ("memory.created", "Memory Created"),
                    ("memory.updated", "Memory Updated"),
                    ("memory.deleted", "Memory Deleted"),
                    ("brief.generated", "Brief Generated"),
                    ("user.created", "User Created"),
                    ("user.updated", "User Updated"),
                    ("user.deactivated", "User Deactivated"),
                    ("user.reactivated", "User Reactivated"),
                    ("property.created", "Property Created"),
                    ("property.updated", "Property Updated"),
                    ("property.deleted", "Property Deleted"),
                    ("service.created", "Service Created"),
                    ("service.updated", "Service Updated"),
                    ("service.deleted", "Service Deleted"),
                ],
                db_index=True,
                help_text="Type of event that occurred",
                max_length=50,
            ),
        ),
    ]
