# Generated by Django 5.0.14 on 2026-01-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_entity_type_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("booking", "Booking"),
                    ("job", "Job"),
                    ("user", "User"),
                    ("property", "Property"),
                    ("service", "Service"),
                    ("memory", "Memory"),
                    ("technician", "Technician"),
                    ("brief", "Brief"),
                    ("recurring_series", "Recurring Series"),
                ],
                db_index=True,
                help_text="Type of entity this event relates to",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("booking.created", "Booking Created"),
                    ("booking.confirmed", "Booking Confirmed"),
                    ("booking.cancelled", "Booking Cancelled"),
                    ("booking.completed", "Booking Completed"),
                    ("booking.fulfilled", "Booking Fulfilled"),
                    ("booking.rescheduled", "Booking Rescheduled"),
                    ("booking.job_generated", "Booking Job Generated"),
                    ("booking.generated_from_series", "Booking Generated From Series"),
                    ("booking.reschedule_requested", "Booking Reschedule Requested"),
                    ("booking.reschedule_confirmed", "Booking Reschedule Confirmed"),
                    ("booking.reschedule_rejected", "Booking Reschedule Rejected"),
                    ("series.paused", "Series Paused"),
                    ("series.resumed", "Series Resumed"),
                    ("series.ended", "Series Ended"),
                    ("series.skip_next", "Series Skip Next"),
                    ("series.skip_cancelled", "Series Skip Cancelled"),
                    ("series.date_skipped", "Series Date Skipped"),
                    ("series.occurrence_skipped", "Series Occurrence Skipped"),
                    ("series.occurrence_rescheduled", "Series Occurrence Rescheduled"),
                    ("series.exception_reverted", "Series Exception Reverted"),
                    ("job.assigned", "Job Assigned"),
                    ("job.claimed", "Job Claimed"),
                    ("job.released", "Job Released"),
                    ("job.started", "Job Started"),
                    ("job.completed", "Job Completed"),
                    ("job.cancelled", "Job Cancelled"),
                    ("job.generated_from_series", "Job Generated From Series"),
                    ("technician.assigned", "Technician Assigned"),
                    ("technician.unassigned", "Technician Unassigned"),
                    ("technician.checked_in", "Technician Checked In"),
                    ("technician.checked_out", "Technician Checked Out"),
                    ("technician.skills_updated", "Technician Skills Updated"),
                    ("memory.created", "Memory Created"),
                    ("memory.updated", "Memory Updated"),
                    ("memory.deleted", "Memory Deleted"),
                    ("brief.generated", "Brief Generated"),
                    ("user.created", "User Created"),
                    ("user.updated", "User Updated"),
                    ("user.deactivated", "User Deactivated"),
                    ("user.reactivated", "User Reactivated"),
                    ("property.created", "Property Created"),
                    ("property.updated", "Property Updated"),
                    ("property.deleted", "Property Deleted"),
                    ("service.created", "Service Created"),
                    ("service.updated", "Service Updated"),
                    ("service.deleted", "Service Deleted"),
                ],
                db_index=True,
                help_text="Type of event that occurred",
                max_length=50,
            ),
        ),
    ]
