# Generated by Django 6.0.3 on 2026-03-22 12:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_locked', models.BooleanField(db_index=True, default=False, help_text='Whether the property linkage is locked (prevents changing property)')),
                ('title', models.CharField(blank=True, help_text='Optional title for the session (can be auto-generated)', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='active', help_text='Current status of the session', max_length=20)),
                ('system_context', models.JSONField(blank=True, default=dict, help_text='System rules and context for this intake session')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of the last message in this session', null=True)),
                ('message_count', models.IntegerField(default=0, help_text='Total number of messages in this session', validators=[django.core.validators.MinValueValidator(0)])),
                ('onboarding_complete', models.BooleanField(db_index=True, default=False, help_text='Whether all required facts have been collected')),
                ('onboarding_completed_at', models.DateTimeField(blank=True, help_text='When onboarding was marked complete', null=True)),
                ('fact_check_cache', models.JSONField(blank=True, default=dict, help_text='Cached results of fact checking')),
                ('fact_check_cache_updated_at', models.DateTimeField(blank=True, help_text='When fact check cache was last updated', null=True)),
            ],
            options={
                'db_table': 'intake_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalApplicationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('applied', 'Applied Successfully'), ('rejected', 'Rejected'), ('failed', 'Application Failed')], db_index=True, help_text='Result of the application attempt', max_length=20)),
                ('affected_entity_type', models.CharField(blank=True, help_text='Type of entity that was created/updated (property, memory, etc.)', max_length=50)),
                ('affected_entity_id', models.UUIDField(blank=True, db_index=True, help_text='ID of the entity that was created/updated', null=True)),
                ('source_message_id', models.UUIDField(blank=True, db_index=True, help_text='ID of the chat message that generated this proposal', null=True)),
                ('source_media_attachments', models.JSONField(blank=True, default=list, help_text='Media attachments from the source message')),
                ('previous_state', models.JSONField(blank=True, help_text='State before application (for updates)', null=True)),
                ('new_state', models.JSONField(blank=True, help_text='State after application', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code if application failed', max_length=100)),
                ('error_message', models.TextField(blank=True, help_text='Detailed error message if application failed')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('validation_passed', models.BooleanField(default=True, help_text='Whether validation passed before application')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors encountered')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the request')),
                ('request_id', models.CharField(blank=True, help_text='Request ID for correlation', max_length=100)),
            ],
            options={
                'db_table': 'proposal_application_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_type', models.CharField(choices=[('property_create', 'Create Property'), ('property_update', 'Update Property'), ('room_create', 'Create Room'), ('room_update', 'Update Room'), ('memory_create', 'Create Memory/Note'), ('memory_update', 'Update Memory/Note'), ('preference_create', 'Create Preference'), ('preference_update', 'Update Preference'), ('do_rule_create', 'Create Do Rule'), ('do_rule_update', 'Update Do Rule'), ('dont_rule_create', "Create Don't Rule"), ('dont_rule_update', "Update Don't Rule"), ('photo_create', 'Create Reference Photo'), ('photo_update', 'Update Reference Photo')], db_index=True, help_text='Type of update being proposed', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('superseded', 'Superseded')], db_index=True, default='pending', help_text='Current status of this proposal', max_length=20)),
                ('target_entity_id', models.UUIDField(blank=True, db_index=True, help_text='ID of the entity this proposal affects (null for creates)', null=True)),
                ('target_entity_type', models.CharField(blank=True, help_text='Type of entity (property, room, memory, etc.)', max_length=50)),
                ('proposed_data', models.JSONField(help_text='Structured payload of the proposed update')),
                ('content_hash', models.CharField(db_index=True, help_text='Hash of proposed_data for deduplication', max_length=64)),
                ('summary', models.TextField(blank=True, help_text='Human-readable summary of what this proposal does')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this proposal was reviewed', null=True)),
            ],
            options={
                'db_table': 'intake_update_proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, help_text='Role of the message sender', max_length=20)),
                ('content', models.TextField(help_text='Text content of the message')),
                ('media_attachments', models.JSONField(blank=True, default=list, help_text='List of media attachment references [{blob_name, content_type, file_name}]')),
                ('sequence_number', models.IntegerField(db_index=True, help_text='Order of this message within the session')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (model used, token counts, etc.)')),
                ('in_reply_to', models.ForeignKey(blank=True, help_text='The user message this assistant message responds to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='intake.intakemessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'intake_messages',
                'ordering': ['session', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='IntakeMessageUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, help_text='Date in YYYY-MM-DD format')),
                ('count', models.IntegerField(default=0, help_text='Number of LLM calls made on this date', validators=[django.core.validators.MinValueValidator(0)])),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'intake_message_usage',
            },
        ),
    ]
