# Generated by Django 6.0.3 on 2026-03-22 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
        ('properties', '0002_propertymemory_property_access_instructions_and_more'),
        ('tenants', '0002_alter_tenant_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intakemessageusage',
            name='user',
            field=models.ForeignKey(help_text='User who made the LLM request', on_delete=django.db.models.deletion.CASCADE, related_name='intake_message_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intakesession',
            name='client',
            field=models.ForeignKey(help_text='Client user who owns this session', on_delete=django.db.models.deletion.CASCADE, related_name='intake_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intakesession',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Property this session relates to (if known). Once set, cannot be changed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sessions', to='properties.property'),
        ),
        migrations.AddField(
            model_name='intakesession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='intakemessage',
            name='session',
            field=models.ForeignKey(help_text='Session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='intake.intakesession'),
        ),
        migrations.AddField(
            model_name='proposalapplicationauditlog',
            name='applied_by',
            field=models.ForeignKey(blank=True, help_text='User who applied/rejected this proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_application_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalapplicationauditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='updateproposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed this proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='updateproposal',
            name='session',
            field=models.ForeignKey(help_text='Session this proposal was generated in', on_delete=django.db.models.deletion.CASCADE, related_name='update_proposals', to='intake.intakesession'),
        ),
        migrations.AddField(
            model_name='updateproposal',
            name='source_message',
            field=models.ForeignKey(help_text='The assistant message that generated this proposal', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='intake.intakemessage'),
        ),
        migrations.AddField(
            model_name='updateproposal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='proposalapplicationauditlog',
            name='proposal',
            field=models.ForeignKey(help_text='The proposal this audit entry relates to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='intake.updateproposal'),
        ),
        migrations.AddIndex(
            model_name='intakemessageusage',
            index=models.Index(fields=['tenant', 'user', 'date'], name='intake_mess_tenant__188a38_idx'),
        ),
        migrations.AddIndex(
            model_name='intakemessageusage',
            index=models.Index(fields=['tenant', 'date'], name='intake_mess_tenant__92a34f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intakemessageusage',
            unique_together={('tenant', 'user', 'date')},
        ),
        migrations.AddIndex(
            model_name='intakesession',
            index=models.Index(fields=['tenant', 'client', 'status'], name='intake_sess_tenant__96d5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='intakesession',
            index=models.Index(fields=['tenant', 'client', '-updated_at'], name='intake_sess_tenant__2863f4_idx'),
        ),
        migrations.AddIndex(
            model_name='intakesession',
            index=models.Index(fields=['tenant', 'property', 'status'], name='intake_sess_tenant__b8cf2b_idx'),
        ),
        migrations.AddIndex(
            model_name='intakesession',
            index=models.Index(fields=['client', '-last_message_at'], name='intake_sess_client__5a9f30_idx'),
        ),
        migrations.AddIndex(
            model_name='intakemessage',
            index=models.Index(fields=['session', 'sequence_number'], name='intake_mess_session_4c8e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='intakemessage',
            index=models.Index(fields=['session', 'role'], name='intake_mess_session_4b8d13_idx'),
        ),
        migrations.AddIndex(
            model_name='intakemessage',
            index=models.Index(fields=['tenant', 'session', '-created_at'], name='intake_mess_tenant__3c93a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='intakemessage',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_number'), name='unique_session_sequence'),
        ),
        migrations.AddIndex(
            model_name='updateproposal',
            index=models.Index(fields=['session', 'status'], name='intake_upda_session_e56170_idx'),
        ),
        migrations.AddIndex(
            model_name='updateproposal',
            index=models.Index(fields=['session', 'proposal_type'], name='intake_upda_session_f77183_idx'),
        ),
        migrations.AddIndex(
            model_name='updateproposal',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='intake_upda_tenant__34f827_idx'),
        ),
        migrations.AddIndex(
            model_name='updateproposal',
            index=models.Index(fields=['content_hash'], name='intake_upda_content_805a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='updateproposal',
            index=models.Index(fields=['source_message'], name='intake_upda_source__47df85_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalapplicationauditlog',
            index=models.Index(fields=['proposal', '-created_at'], name='proposal_ap_proposa_86672f_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalapplicationauditlog',
            index=models.Index(fields=['tenant', 'result', '-created_at'], name='proposal_ap_tenant__2b99f7_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalapplicationauditlog',
            index=models.Index(fields=['applied_by', '-created_at'], name='proposal_ap_applied_f6b281_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalapplicationauditlog',
            index=models.Index(fields=['affected_entity_type', 'affected_entity_id'], name='proposal_ap_affecte_192452_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalapplicationauditlog',
            index=models.Index(fields=['source_message_id'], name='proposal_ap_source__c9842f_idx'),
        ),
    ]
