# Generated by Django 6.0.3 on 2026-03-22 02:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_service_request_domain'),
        ('pricing', '0001_service_request_domain'),
        ('properties', '0001_service_request_domain'),
        ('tenants', '0002_alter_tenant_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address_raw', models.TextField()),
                ('address_normalized', models.JSONField(blank=True, help_text='Structured address after normalization. Shape: {street, city, state, zip, country, lat, lng, confidence}. Written by normalization service or operator, never by intake form.', null=True)),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_type', models.CharField(choices=[('standard_cleaning', 'Standard Cleaning'), ('deep_clean', 'Deep Clean'), ('organizing', 'Organizing'), ('move_in_out', 'Move In / Move Out'), ('post_construction', 'Post Construction'), ('other', 'Other')], db_index=True, max_length=64)),
                ('timing_preference', models.JSONField(blank=True, default=dict, help_text='Canonical keys: preferred_days, preferred_time_of_day, date_range_start, date_range_end, flexibility, notes — validated at API layer.')),
                ('notes', models.TextField(blank=True)),
                ('media_refs', models.JSONField(blank=True, default=list, help_text='List of validated refs: {type, storage_key, url?} — no blobs.')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('priced', 'Priced'), ('converted', 'Converted'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('form', 'Form'), ('api', 'API'), ('import', 'Import')], db_index=True, default='form', max_length=20)),
                ('internal_operator_notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('converted_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_service_requests', to='jobs.job')),
                ('latest_price_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing.pricesnapshot')),
                ('property_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='service_req_tenant__dd4058_idx'), models.Index(fields=['tenant', 'service_type', '-created_at'], name='service_req_tenant__8af0e4_idx')],
            },
        ),
    ]
