# Generated by Django 6.0.3 on 2026-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_alter_servicerequest_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='address_normalized',
            field=models.JSONField(blank=True, help_text='Structured address after normalization. Shape: {street, city, state, zip, country, lat, lng, confidence}. Written by the normalization service or an operator only.', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='address_raw',
            field=models.TextField(help_text='Verbatim address as submitted by the customer.'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='media_refs',
            field=models.JSONField(blank=True, default=list, help_text='References to attached media. No blobs stored here. Shape: [{type, storage_key, url?}]'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='timing_preference',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible scheduling window. Shape: {preferred_days[], preferred_time_of_day, date_range_start, date_range_end, flexibility, notes}. Not strict scheduling — no datetime precision.'),
        ),
    ]
