# Generated by Django 6.0.3 on 2026-03-24 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_assigned_to'),
        ('pricing', '0002_service_request_domain'),
        ('properties', '0003_idealconditionphoto_uploaded_by_and_more'),
        ('service_requests', '0003_alter_servicerequest_address_normalized_and_more'),
        ('tenants', '0004_tenant_logo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOfferingSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'service_offering_skills',
                'ordering': ['sort_order', 'skill__label'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('reporting_category', models.CharField(choices=[('standard_cleaning', 'Standard Cleaning'), ('deep_clean', 'Deep Clean'), ('organizing', 'Organizing'), ('move_in_out', 'Move In / Move Out'), ('post_construction', 'Post Construction'), ('other', 'Other')], default='other', help_text='Stored on ServiceRequest.service_type when this offering is selected — keeps reporting aligned with the global ServiceType enum.', max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'service_offerings',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='service_requests.serviceoffering'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['tenant', 'service_offering', '-created_at'], name='service_req_tenant__8e951a_idx'),
        ),
        migrations.AddField(
            model_name='serviceofferingskill',
            name='service_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_skills', to='service_requests.serviceoffering'),
        ),
        migrations.AddField(
            model_name='serviceofferingskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_skill_links', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='service_offerings', through='service_requests.ServiceOfferingSkill', to='jobs.skill'),
        ),
        migrations.AddConstraint(
            model_name='serviceofferingskill',
            constraint=models.UniqueConstraint(fields=('service_offering', 'skill'), name='uniq_service_offering_skill'),
        ),
        migrations.AddIndex(
            model_name='serviceoffering',
            index=models.Index(fields=['tenant', 'is_active', 'sort_order'], name='service_off_tenant__772552_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceoffering',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_service_offering_tenant_slug'),
        ),
    ]
