# Generated by Django 6.0.3 on 2026-03-22 02:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_cents', models.BigIntegerField()),
                ('subtotal_cents', models.BigIntegerField(default=0)),
                ('line_items', models.JSONField(default=list)),
                ('inputs_used', models.JSONField(default=dict, help_text='Structured pricing inputs copied from ServiceRequest at quote time')),
                ('pricing_engine_version', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'price_snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
