# Generated by Django 6.0.3 on 2026-03-22 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_service_request_domain'),
        ('service_requests', '0001_service_request_domain'),
        ('tenants', '0002_alter_tenant_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesnapshot',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['tenant', 'service_request', '-created_at'], name='price_snaps_tenant__aa7cea_idx'),
        ),
    ]
