steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/morgan-api:$COMMIT_SHA', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/morgan-api:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'morgan-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/morgan-api:$COMMIT_SHA'
    - '--service-account'
    - '754882757416-compute@developer.gserviceaccount.com'
    - '--region'
    - 'us-east4'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/morgan-api:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY