# Generated by Django 5.0.14 on 2026-03-19 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Stable identifier (e.g., 'nj_essex_county')", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'Essex County, NJ')", max_length=255)),
                ('short_name', models.CharField(blank=True, help_text="Abbreviated name for UI (e.g., 'Essex County')", max_length=100)),
                ('state', models.CharField(db_index=True, help_text="State/province (e.g., 'NJ', 'New Jersey')", max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this region is currently available for selection')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extensible metadata (geo bounds, zip codes, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent region for hierarchical structures', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='technicians.serviceregion')),
            ],
            options={
                'db_table': 'service_regions',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onboarding_status', models.CharField(choices=[('pending_onboarding', 'Pending Onboarding'), ('submitted', 'Submitted for Review'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='pending_onboarding', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Internal notes from the reviewer (visible to admins only)')),
                ('suspension_reason', models.TextField(blank=True, help_text='Reason for suspension (visible to the technician)')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Extensible storage for additional onboarding fields')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Technician preferences (notifications, availability, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_technician_profiles', to=settings.AUTH_USER_MODEL)),
                ('service_regions', models.ManyToManyField(blank=True, help_text='Regions where this technician is willing to work', related_name='technician_profiles', to='technicians.serviceregion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profiles', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'technician_profiles',
            },
        ),
        migrations.CreateModel(
            name='TechnicianApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company / Team')], db_index=True, default='individual', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, help_text='Populated when applicant_type=company', max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('service_area', models.JSONField(blank=True, default=dict, help_text="Geographic coverage. Soft schema: {'counties': ['Essex', 'Hudson'], 'service_region_keys': ['nj_essex_county'], 'max_travel_miles': 25, 'notes': '...'}")),
                ('availability', models.JSONField(blank=True, default=dict, help_text="When the applicant can work. Soft schema: {'days': ['mon','tue','wed'], 'hours': {'start': '08:00', 'end': '18:00'}, 'start_date': '2025-02-01', 'hours_per_week': 30, 'notes': '...'}")),
                ('experience', models.JSONField(blank=True, default=dict, help_text="Work history & qualifications. Soft schema: {'years_cleaning': 3, 'prior_employers': [...], 'has_own_supplies': true, 'has_vehicle': true, 'certifications': [...], 'references': [...]}")),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text="Declared skills/service types. Soft schema: {'skill_keys': ['standard_clean','deep_clean'], 'specialties': [...], 'team_size': 1, 'languages': [...]}")),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Free-form Q&A payload for tenant-specific questions. Keyed by question slug. Shape governed by schema_version.')),
                ('schema_version', models.PositiveIntegerField(default=1, help_text='Version of the questionnaire schema used to populate `answers`.')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the applicant submitted (may differ from created_at if drafts are supported).', null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Internal operator notes. Never shown to the applicant.')),
                ('rejection_reason', models.TextField(blank=True, help_text='Optional reason captured on rejection. May be shared with applicant.')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text="Where this application originated (e.g. 'public_form', 'operator_entry', 'referral').", max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='System/provenance metadata (utm params, IP, user agent, referral codes, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_user', models.ForeignKey(blank=True, help_text='User account created/linked when this application was approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Operator who most recently reviewed this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_technician_applications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_applications', to='tenants.tenant')),
                ('converted_technician_profile', models.ForeignKey(blank=True, help_text='TechnicianProfile created/linked on approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_applications', to='technicians.technicianprofile')),
            ],
            options={
                'db_table': 'technician_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceregion',
            index=models.Index(fields=['state', 'is_active'], name='service_reg_state_b2fd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceregion',
            index=models.Index(fields=['is_active'], name='service_reg_is_acti_15d40a_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['tenant', 'onboarding_status'], name='technician__tenant__729139_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicianprofile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_technician_profile_per_user'),
        ),
        migrations.AddIndex(
            model_name='technicianapplication',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='technician__tenant__3e9fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianapplication',
            index=models.Index(fields=['tenant', 'email'], name='technician__tenant__8cd6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianapplication',
            index=models.Index(fields=['tenant', 'applicant_type', 'status'], name='technician__tenant__94c883_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianapplication',
            index=models.Index(fields=['tenant', '-created_at'], name='technician__tenant__b9c7b8_idx'),
        ),
    ]
