# Generated by Django 5.0.14 on 2026-03-20 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_technician_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianapplication',
            name='converted_by',
            field=models.ForeignKey(blank=True, help_text='Operator who executed the conversion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_technician_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='application_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable snapshot of the TechnicianApplication at conversion time. Used for outcome correlation and audit.'),
        ),
    ]
