# Generated by Django 6.0.3 on 2026-03-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0003_application_form'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applicationform',
            new_name='application_tenant__d68dde_idx',
            old_name='application_tenant_i_7a8b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationform',
            new_name='application_tenant__d40dee_idx',
            old_name='application_tenant_i_9d0e1f_idx',
        ),
        migrations.RenameIndex(
            model_name='technicianapplication',
            new_name='technician__applica_e0d74d_idx',
            old_name='technician_applicatio_af_idx',
        ),
    ]
