# Generated by Django 6.0.3 on 2026-03-22 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_booking_domain'),
        ('technicians', '0005_formfield'),
        ('tenants', '0002_alter_tenant_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianInboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('operator', 'Operator'), ('client', 'Client'), ('system', 'System'), ('technician', 'Technician')], db_index=True, max_length=32)),
                ('sender_name', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'technician_inbox_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianInboxMessageReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'technician_inbox_message_receipts',
            },
        ),
        migrations.CreateModel(
            name='TechnicianInboxThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thread_type', models.CharField(choices=[('operator_direct', 'Operator direct'), ('client_job', 'Client job'), ('system_alert', 'System alert')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=512)),
                ('participant_name', models.CharField(blank=True, default='', max_length=255)),
                ('participant_avatar_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('last_activity_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'technician_inbox_threads',
                'ordering': ['-is_pinned', '-last_activity_at'],
            },
        ),
        migrations.AddField(
            model_name='technicianinboxmessage',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_inbox_messages', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='technicianinboxmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianinboxmessage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='technicianinboxmessagereceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='technicians.technicianinboxmessage'),
        ),
        migrations.AddField(
            model_name='technicianinboxmessagereceipt',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_read_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianinboxmessagereceipt',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='technicianinboxthread',
            name='client_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_inbox_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianinboxthread',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_inbox_threads', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='technicianinboxthread',
            name='operator_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_inbox_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianinboxthread',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianinboxthread',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='technicianinboxmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='technicians.technicianinboxthread'),
        ),
        migrations.AddConstraint(
            model_name='technicianinboxmessagereceipt',
            constraint=models.UniqueConstraint(fields=('message', 'reader'), name='uniq_inbox_msg_reader'),
        ),
        migrations.AddIndex(
            model_name='technicianinboxthread',
            index=models.Index(fields=['tenant', 'technician', '-last_activity_at'], name='technician__tenant__f039ef_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianinboxthread',
            index=models.Index(fields=['technician', 'thread_type'], name='technician__technic_39bbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianinboxmessage',
            index=models.Index(fields=['thread', 'created_at'], name='technician__thread__85232b_idx'),
        ),
    ]
