# Generated by Django 6.0.3 on 2026-03-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0006_technician_inbox'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='formfield',
            new_name='application_form_id_7d86ce_idx',
            old_name='application_form_fi_form_pos_idx',
        ),
        migrations.AlterField(
            model_name='formfield',
            name='validations',
            field=models.JSONField(blank=True, default=dict, help_text='Field-level validation rules. See model docstring for schema.'),
        ),
    ]
