# Generated by Django 6.0.3 on 2026-03-22 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_service_request_domain'),
        ('service_requests', '0001_service_request_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='service_requests.servicerequest'),
        ),
    ]
