# Generated by Django 6.0.3 on 2026-03-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_domain'),
        ('jobs', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='bookings.booking'),
        ),
    ]
