# Generated by Django 6.0.3 on 2026-03-22 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_service_request_domain'),
        ('tenants', '0002_alter_tenant_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory_type', models.CharField(choices=[('do_rule', 'Do Rule'), ('dont_rule', "Don't Rule"), ('product_preference', 'Product Preference'), ('personal_sensitivity', 'Personal Sensitivity'), ('note', 'Note')], db_index=True, max_length=40)),
                ('level', models.CharField(default='property', max_length=32)),
                ('room_name', models.CharField(blank=True, max_length=255)),
                ('surface_name', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('use_product', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'property_memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='access_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='property',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size_sqft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='square_feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='IdealConditionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(blank=True, max_length=255)),
                ('surface_name', models.CharField(blank=True, max_length=255)),
                ('location_description', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=512)),
                ('file_url', models.URLField(blank=True, max_length=2048)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2048)),
                ('caption', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_condition_photos', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ideal_condition_photos',
                'ordering': ['created_at'],
            },
        ),
    ]
