# Generated by Django 6.0.3 on 2026-03-22 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertymemory_property_access_instructions_and_more'),
        ('tenants', '0002_alter_tenant_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idealconditionphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ideal_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertymemory',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_property_memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertymemory',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertymemory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='propertymemory',
            index=models.Index(fields=['tenant', 'property', 'memory_type'], name='property_me_tenant__7fbfb6_idx'),
        ),
    ]
