# Generated by Django 5.0.14 on 2026-01-08 00:11

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="IANA timezone (e.g., 'America/New_York', 'Europe/London')",
                max_length=50,
                validators=[apps.tenants.models.validate_timezone],
            ),
        ),
    ]
