# Generated by Django 6.0.3 on 2026-03-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_skill"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="jobs.skill"
            ),
        ),
    ]
