# Generated by Django 6.0.3 on 2026-03-22 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial_recurring_series'),
        ('properties', '0003_idealconditionphoto_uploaded_by_and_more'),
        ('tenants', '0002_alter_tenant_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=64)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('scheduled_end_time', models.TimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('one_time', 'One-time'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], db_index=True, default='one_time', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], db_index=True, default='draft', max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pricing_breakdown', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.property')),
                ('recurring_service_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.recurringserviceseries')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', '-scheduled_date'], name='bookings_tenant__89837b_idx'), models.Index(fields=['tenant', 'client_name'], name='bookings_tenant__455e7d_idx')],
            },
        ),
    ]
