"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Determine environment
ENV = os.getenv('APP_MODE', 'development')  # Default to 'development'

# Load the appropriate .env file
if ENV == 'staging':
    load_dotenv('.env.staging')
else:
    load_dotenv('.env')

# Add channels
ASGI_APPLICATION = "api.asgi.application"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# In development (DEBUG = True), Django doesn't check ALLOWED_HOSTS
# In production (DEBUG = False), Django will only serve these hosts
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'dev4.undock.ngrok.io',
    # 'morgan-staging.web.app',
    # 'morgan-api-754882757416.us-east4.run.app'
]
CORS_ALLOW_ALL_ORIGINS = DEBUG  # True in dev, False in prod
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8686',
    'https://dev4.undock.ngrok.io',
    # 'https://morgan-staging.web.app',
    # 'https://morgan-api-754882757416.us-east4.run.app',
]
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control'
]

CSRF_TRUSTED_ORIGINS = [
    'https://*.run.app',  # For Cloud Run URLs
    'https://*.web.app',
    'http://localhost:8000',
    'http://localhost:8686'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'corsheaders',
<<<<<<< HEAD
    # 'knowledgebase'
=======
    'agent_chat_api'
>>>>>>> 841269cafde83fe6014a93f44959c790b8e0a23b
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Conditional security settings for production
if not DEBUG:  # Only apply in production
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True') == 'True'
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True') == 'True'
    SECURE_BROWSER_XSS_FILTER = os.getenv('SECURE_BROWSER_XSS_FILTER', 'True') == 'True'
    SECURE_CONTENT_TYPE_NOSNIFF = os.getenv('SECURE_CONTENT_TYPE_NOSNIFF', 'True') == 'True'
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Set the environment variable for Google SDK
if DEBUG:
    GOOGLE_CLOUD_CREDENTIALS = os.getenv("GOOGLE_CLOUD_CREDENTIALS")
    GOOGLE_CLOUD_CREDENTIALS_PATH = os.path.join(BASE_DIR, GOOGLE_CLOUD_CREDENTIALS)
    
GOOGLE_CLOUD_PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT", "matterseek-staging")
GOOGLE_CLOUD_LOCATION = os.getenv("GOOGLE_CLOUD_LOCATION", "us-east4")
GOOGLE_CLOUD_STORAGE_BUCKET = os.getenv("GOOGLE_CLOUD_STORAGE_BUCKET", "matterseek-staging")
GOOGLE_SERVICE_ACCOUNT = os.getenv("GOOGLE_SERVICE_ACCOUNT", "matterseek@matterseek-staging.iam.gserviceaccount.com")
GOOGLE_CLOUD_RUN_URL = os.getenv("API_URL", "https://dev4.undock.ngrok.io")

LOGFIRE_TOKEN = os.getenv("LOGFIRE_TOKEN")
